version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.3
    executor: ruby/default
    environment:
        TZ: "Europe/Zurich"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a0:8c:53:5c:1d:28:e5:ed:3f:b3:91:55:78:f9:b8:45"
      - checkout
      - run:
          name: Set Zurich timezone
          command: ln -snf /usr/share/zoneinfo/Europe/Zurich /etc/localtime && echo Europe/Zurich > /etc/timezone
      - run:
          name: Install rsync
          command: apt update && apt install -y rsync
      - ruby/install-deps:
          bundler-version: '2.1.4'
      - run:
          name: Jekyll build
          command: bundle exec jekyll build --destination tmp
      - run:
          name: checkout publish branch
          command: |
            git fetch
            git branch -f publish origin/publish
      - run:
          name: Clear publish directory
          command: rm -rf publish
      - run:
          name: Cone the publish branch to publish. This step was failing.
          command: |
            git fetch
            git clone -l -b publish . publish
      - run:
          name: Merge the built files with publish.
          command: rsync -rvLk --exclude='.git'--delete tmp/ publish
      - run:
          name: Copy the circleci configuration to publish to prevent extra builds.
          command: rsync -rvLk .circleci publish/
      - run:
          name: push the files in publish to publish
          command: |
            cd publish
            echo ../CNAME CNAME
            git config --global user.email "conan747@circleci.com"
            git config --global user.name "circleci"
            git add .
            git commit -m "Built from circleci" || echo "Not committing."
            git push
            cd ..
            git push origin publish

workflows:
  version: 2
  after_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - dev
    jobs:
      - build
